# Generated by Django 6.0.6 on 2026-06-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Computed at creation; locked', max_digits=10)),
                ('price_breakdown', models.JSONField(default=list, help_text='Night-by-night rate detail')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('converted', 'Converted')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, help_text='Set when guest enters payment flow - prevents expiry race', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_breakdown', models.JSONField(default=list)),
                ('reason', models.CharField(choices=[('initial', 'Initial'), ('guest_request', 'Guest Request'), ('hotel_initiated', 'Hotel Initiated'), ('no_show', 'No-Show'), ('system', 'System')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changes_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_ref', models.CharField(blank=True, max_length=40, unique=True)),
                ('check_in', models.DateField(help_text='Point-in-time snapshot (latest)')),
                ('check_out', models.DateField(help_text='Point-in-time snapshot (latest)')),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_breakdown', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('completed', 'Completed')], default='pending_payment', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('extranet', 'Extranet'), ('channel_manager', 'Channel Manager')], default='web', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('modification_policy', models.CharField(choices=[('flexible', 'Flexible'), ('moderate', 'Moderate'), ('strict', 'Strict')], default='moderate', max_length=10)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
