# Generated by Django 6.0.6 on 2026-06-13 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.mealplan'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype'),
        ),
        migrations.AddField(
            model_name='bookingcart',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.mealplan'),
        ),
        migrations.AddField(
            model_name='bookingcart',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.bookingcart'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_rooms', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='bookingversion',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingversion',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.mealplan'),
        ),
        migrations.AddField(
            model_name='bookingversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingcart',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_aec611_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcart',
            index=models.Index(fields=['session_key'], name='bookings_bo_session_bf18db_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in'], name='bookings_bo_status_8296ff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ref'], name='bookings_bo_booking_c0d7c7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest'], name='bookings_bo_guest_i_05b863_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingroom',
            unique_together={('booking', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='bookingversion',
            unique_together={('booking', 'version_number')},
        ),
    ]
