# Generated by Django 6.0.6 on 2026-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, help_text='Used for lookup/dedup', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('marketing_consent', models.BooleanField(default=False, help_text='GDPR: marketing consent')),
                ('gdpr_erasure_requested', models.BooleanField(default=False, help_text='Soft anonymisation flag')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='guests_gues_email_e4fe59_idx')],
            },
        ),
    ]
