# Generated by Django 6.0.6 on 2026-06-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('bathroom', 'Bathroom'), ('comfort', 'Comfort'), ('food', 'Food & Drink')], default='comfort', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('short_description', models.CharField(help_text='Used in listing cards', max_length=200)),
                ('full_description', models.TextField(help_text='Used on detail page')),
                ('max_capacity', models.PositiveSmallIntegerField(default=2)),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=2)),
                ('size_sqm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('view_type', models.CharField(choices=[('garden', 'Garden'), ('pool', 'Pool'), ('terrace', 'Terrace'), ('balcony', 'Balcony')], default='garden', max_length=20)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, default=0, help_text='Fallback when no RateRule exists', max_digits=10)),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='rooms/types/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(help_text='Required for accessibility/SEO', max_length=200)),
                ('is_hero', models.BooleanField(default=False, help_text='The primary card/header image')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=10)),
                ('floor', models.PositiveSmallIntegerField()),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only notes')),
                ('is_active', models.BooleanField(default=True, help_text='Out-of-service flag')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['room_type', 'is_active'], name='rooms_room_room_ty_c54182_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show prominently on listing cards')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.amenity')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Type Amenities',
                'unique_together': {('room_type', 'amenity')},
            },
        ),
    ]
