# Generated by Django 6.0.6 on 2026-06-13 15:02

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Used on the booking review page')),
                ('includes_items', models.TextField(blank=True, help_text='Bullet list of inclusions')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Higher = evaluated first when ranges overlap')),
            ],
            options={
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='StopSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_sells', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_rooms', models.PositiveSmallIntegerField(default=1, help_text='Managed by extranet')),
                ('rooms_on_hold', models.PositiveSmallIntegerField(default=0)),
                ('rooms_sold', models.PositiveSmallIntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotments', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Inventory Allotment',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='inventory_i_date_f61180_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rooms_on_hold__lte', django.db.models.expressions.CombinedExpression(models.F('total_rooms'), '-', models.F('rooms_sold')))), name='allotment_not_overbooked')],
                'unique_together': {('room_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_nights', models.PositiveSmallIntegerField(default=1)),
                ('max_nights', models.PositiveSmallIntegerField(blank=True, default=None, help_text='NULL = no maximum', null=True)),
                ('days_of_week_mask', models.PositiveSmallIntegerField(default=127, help_text='7-bit bitmask (bit 0 = Monday)')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_rules', to='inventory.mealplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_rules', to='rooms.roomtype')),
                ('season', models.ForeignKey(blank=True, help_text='NULL = applies outside any season', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.season')),
            ],
            options={
                'indexes': [models.Index(fields=['room_type', 'meal_plan', 'season'], name='inventory_r_room_ty_31a13f_idx'), models.Index(fields=['room_type', 'meal_plan', 'is_active'], name='inventory_r_room_ty_5c01ae_idx')],
            },
        ),
    ]
