# Generated by Django 5.2.9 on 2026-02-27 14:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('superior', 'Superior'), ('deluxe', 'Deluxe'), ('family', 'Family')], db_index=True, default='standard', max_length=20)),
                ('size_sqm', models.DecimalField(decimal_places=2, help_text='Room size in square metres', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('32.00'))])),
                ('max_adults', models.PositiveSmallIntegerField(default=2)),
                ('max_children', models.PositiveSmallIntegerField(default=2)),
                ('max_capacity', models.PositiveSmallIntegerField(default=5)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('king', 'King'), ('queen', 'Queen')], max_length=50)),
                ('extra_beds_allowed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='rooms/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
